[env]
DISABLE_AUTOUPDATER = 1

[settings]
experimental = true

[tools]
node = "lts"
python = "latest"
uv = "latest"
ripgrep = "latest"
eza = "latest"
starship = "latest"
atuin = "latest"
delta = "latest"
difftastic = "latest"
gcloud = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:ccusage" = "latest"
